package enums;

public enum USER {
    SELLER(true, 0, "seller_urban@mailsac.com","VHt*zzt*wQNu6XS","Mpho", "Etam", "Mbebe",  "", "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NzYyODQ0MDksImV4cCI6MTcwNzM4ODQwOSwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9TRUxMRVIiXSwiZW1haWwiOiJzZWxsZXJfdXJiYW5AbWFpbHNhYy5jb20iLCJpZCI6MTQ4NCwiZmlyc3ROYW1lIjoiTXBobyIsInBpY3R1cmUiOm51bGwsImdvb2dsZUlkIjpudWxsLCJmYWNlYm9va0lkIjpudWxsLCJsaW5rZWRpbklkIjpudWxsLCJnaXRodWJJZCI6bnVsbCwiYXBwbGVJZCI6bnVsbCwiaXNWZXJpZmllZCI6ZmFsc2UsInBob25lIjpudWxsLCJkZXZpY2VUb2tlbiI6IjAiLCJjcmVhdGVkIjp7ImRhdGUiOiIyMDIzLTAxLTE3IDE0OjIxOjI1LjAwMDAwMCIsInRpbWV6b25lX3R5cGUiOjMsInRpbWV6b25lIjoiVVRDIn0sInBheXBhbEFjY291bnRJZCI6bnVsbCwibGF0Ijo1NS44NjQyMzcsImxuZyI6LTQuMjUxODA2LCJicm93c2VyTm90aWZpY2F0aW9ucyI6ZmFsc2UsImFsbG93QW5vbnltb3VzQ2hhdCI6dHJ1ZSwiemlwQ29kZSI6bnVsbCwiZGVsaXZlcnlUeXBlIjpbIkJVWUVSX1BJQ0tVUF9GUk9NX0JSQU5DSCJdLCJtYXhEZWxpdmVyeVJhbmdlIjowLCJmcmVlRGVsaXZlcnlSYW5nZSI6MCwibWluRnJlZURlbGl2ZXJ5T3JkZXIiOjAsInBlck1pbGVDb3N0IjowLCJhdmFpbGFiaWxpdHkiOiIiLCJlc3RpbWF0ZWREZWxpdmVyeVRpbWUiOltdLCJhdmFpbGFiaWxpdHlCcmFuY2giOiIwODowMC0xNzowMCIsIm1pZGRsZU5hbWUiOiJFdGFtIiwibGFzdE5hbWUiOiJNYmViZSIsImZsZXhpYmxlRGVsaXZlcnlPcHRpb25zIjpbXX0.FA2QJrbnY-mX8C6Du3a9npN-ETvnaAz4fW8dnrZZqd5c7yBS7d5iC35JzoIRgkwKpuhwX7wtv0wKn-KpAIfXAkibyk2BcQxuKXscVgxWN-OfD98gkYty53nAuTBl7u2Wu0ZBQWyr0wjuQLCFr4xsQkJmK08UvzhO81YY1l6Mca130EfNVHjHdIpoP-SjITBAFqafq7zKECiE2hvhU_UjqP-leg94aOFAByUqyqN3U-hNQAkStLDA-A3kZJER86Vh9uYAIu3T68aVFu0ZJuQdYywaRR0ellYhPnjLatbX3AlvSGXeFW1OpW8VTvtzvH0j4F_ory2RBMeVxaa17_02xQ"),
    BUYER(true, 0,"buyer_urban@mailsac.com","VHt*zzt*wQNu6XS","Cristian", "Ronaldo", "Santos",   "", "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NzY3MjQzMjYsImV4cCI6MTcwNzgyODMyNiwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9TRUxMRVIiXSwiZW1haWwiOiJidXllcl91cmJhbkBtYWlsc2FjLmNvbSIsImlkIjoxNDg1LCJmaXJzdE5hbWUiOiJDcmlzdGlhbiIsInBpY3R1cmUiOiIvdXBsb2Fkcy91c2VyLzE0ODUvNjNlNWMwNjQ4YjViMy5wbmciLCJnb29nbGVJZCI6bnVsbCwiZmFjZWJvb2tJZCI6bnVsbCwibGlua2VkaW5JZCI6bnVsbCwiZ2l0aHViSWQiOm51bGwsImFwcGxlSWQiOm51bGwsImlzVmVyaWZpZWQiOmZhbHNlLCJwaG9uZSI6IisxICg1NzUpIDAzOC01MDcwIiwiZGV2aWNlVG9rZW4iOiIwIiwiY3JlYXRlZCI6eyJkYXRlIjoiMjAyMy0wMS0xNyAxNDoyMzo1MS4wMDAwMDAiLCJ0aW1lem9uZV90eXBlIjozLCJ0aW1lem9uZSI6IlVUQyJ9LCJwYXlwYWxBY2NvdW50SWQiOm51bGwsImxhdCI6NTQuOTc0NDE4NSwibG5nIjotMS42NTgzNDk4LCJicm93c2VyTm90aWZpY2F0aW9ucyI6ZmFsc2UsImFsbG93QW5vbnltb3VzQ2hhdCI6dHJ1ZSwiemlwQ29kZSI6bnVsbCwiZGVsaXZlcnlUeXBlIjpbIkJVWUVSX1BJQ0tVUF9GUk9NX0JSQU5DSCIsIlNFTExFUl9GTEVYSUJMRSJdLCJtYXhEZWxpdmVyeVJhbmdlIjowLCJmcmVlRGVsaXZlcnlSYW5nZSI6NywibWluRnJlZURlbGl2ZXJ5T3JkZXIiOjIzMCwicGVyTWlsZUNvc3QiOjIsImF2YWlsYWJpbGl0eSI6IiIsImVzdGltYXRlZERlbGl2ZXJ5VGltZSI6WyI2MF8yIl0sImF2YWlsYWJpbGl0eUJyYW5jaCI6IjA4OjAwLTE3OjAwIiwibWlkZGxlTmFtZSI6IlJvbmFsZG8iLCJsYXN0TmFtZSI6IlNhbnRvcyIsImZsZXhpYmxlRGVsaXZlcnlPcHRpb25zIjpbeyJpZCI6MTE0OCwiZGVsaXZlcnlCeSI6MTY4NCwib3JkZXJCZWdpbiI6MTY4Mywib3JkZXJFbmQiOjE2ODR9XX0.BKjEWUUZU5b6p5elkMarWR9V742LzD93mrAoaXcln84Z2Zn_O762_93QKkf3FzPbmQLK8_dz34f7GkqzxlnAtaWCw92mzmqi_ktmvid0489NH1-5FqD54WQYBjJ1sY1S0AslKB9XQnHdb1ta69dPsDbnDUfYCspVAOXSwwlFAi-lfIY8YXAlPbja5EYdXDV2D7xTBiYWzPGt76YVTRzhVta1c07vbvot-ZfcBMqFwfgXRhIBZ6Q2Vk5mChd_zAThXnRRI-c9Q5Oi9EmHxGrlNDlq56LESiOGxGJ8rh-jXUENZ95A2b6ZT3-7n2L2HJ_8IY5jOZ8VNyr7iKOKfmzIQQ"),
    BUYER2(true, "buyer_urban@mailsac.com","VHt*zzt*wQNu6XS",""),
    EZRA(true, 0, "ezra_test@mailsac.com","Farmer*21", "", "", "", "", "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2Nzc4Njk0ODUsImV4cCI6MTcwODk3MzQ4NSwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9TRUxMRVIiXSwiZW1haWwiOiJlenJhX3Rlc3RAbWFpbHNhYy5jb20iLCJpZCI6MTY0MiwiZmlyc3ROYW1lIjoiRXpyYSIsInBpY3R1cmUiOm51bGwsImdvb2dsZUlkIjpudWxsLCJmYWNlYm9va0lkIjpudWxsLCJsaW5rZWRpbklkIjpudWxsLCJnaXRodWJJZCI6bnVsbCwiYXBwbGVJZCI6bnVsbCwiaXNWZXJpZmllZCI6ZmFsc2UsInBob25lIjoibnVsbCIsImRldmljZVRva2VuIjoiMCIsImNyZWF0ZWQiOnsiZGF0ZSI6IjIwMjMtMDEtMjkgMjA6MjY6MzguMDAwMDAwIiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJVVEMifSwicGF5cGFsQWNjb3VudElkIjpudWxsLCJsYXQiOjQzLjY0MjU2NTcsImxuZyI6LTc5LjM4NzA1NTcsImJyb3dzZXJOb3RpZmljYXRpb25zIjpmYWxzZSwiYWxsb3dBbm9ueW1vdXNDaGF0Ijp0cnVlLCJ6aXBDb2RlIjoiNzc3NzciLCJkZWxpdmVyeVR5cGUiOlsiQlVZRVJfUElDS1VQX0ZST01fQlJBTkNIIiwiU0VMTEVSX0RFTElWRVJZIl0sIm1heERlbGl2ZXJ5UmFuZ2UiOjUsImZyZWVEZWxpdmVyeVJhbmdlIjo1LCJtaW5GcmVlRGVsaXZlcnlPcmRlciI6NSwicGVyTWlsZUNvc3QiOjUsImF2YWlsYWJpbGl0eSI6IiIsImVzdGltYXRlZERlbGl2ZXJ5VGltZSI6WyIxODBfNiJdLCJhdmFpbGFiaWxpdHlCcmFuY2giOiIwODowMC0xNzowMCIsIm1pZGRsZU5hbWUiOiJudWxsIiwibGFzdE5hbWUiOiJBcGF5ZGluIiwiZmxleGlibGVEZWxpdmVyeU9wdGlvbnMiOltdfQ.rfS9A7ETuiFkCtEqJB3y2lxHrlLnraRlU_GP838f2LW2pY4UmEY-hvyQvDQrmHVVnNkEhQ7joCfZKDOiQOP0pgu7NXEIMxfgWxG40H6gtqk-y3OLQwVqfTtB8kf8EelqOSaOOzoNPon82xzPRNJ3zelB3CBEa5dPk4Xocze_D_BjROEotZW8m3utWyX0Yz3z7dXupdZYTjg600Ia8Oe9FQWprgxMZgTgy9dr-pxt7WmMFUOHJ-I7EFJUx-ZOyfv4Oa3zpw6o0BuPqABx3ppqbPZQJxl1Erk_XEt4B3zR48qyOkvTzq4k-yNXwCRiI3j4zKNw4JDZ-jzKMhKxc3KTsA"),
    SELLER_1(true,"seller_urban1@yopmail.com","Seller1/","56789"),
    ALI(true,0,"abc121.@gmail.com","Abc121.@","Ali","","Yavuz","12345","eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NzgwMzkzMTQsImV4cCI6MTcwOTE0MzMxNCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImVtYWlsIjoiYWJjMTIxQGdtYWlsLmNvbSIsImlkIjoxNzUxLCJmaXJzdE5hbWUiOiJhbGkiLCJwaWN0dXJlIjpudWxsLCJnb29nbGVJZCI6bnVsbCwiZmFjZWJvb2tJZCI6bnVsbCwibGlua2VkaW5JZCI6bnVsbCwiZ2l0aHViSWQiOm51bGwsImFwcGxlSWQiOm51bGwsImlzVmVyaWZpZWQiOmZhbHNlLCJwaG9uZSI6Iis5MCA1MDcgMjE2IDUwIDAzIiwiZGV2aWNlVG9rZW4iOiIwIiwiY3JlYXRlZCI6eyJkYXRlIjoiMjAyMy0wMi0wOCAxNTo1NTo1NC4wMDAwMDAiLCJ0aW1lem9uZV90eXBlIjozLCJ0aW1lem9uZSI6IlVUQyJ9LCJwYXlwYWxBY2NvdW50SWQiOm51bGwsImxhdCI6NDAuOTk1MTIzNSwibG5nIjozOS43MDg3MDI2LCJicm93c2VyTm90aWZpY2F0aW9ucyI6ZmFsc2UsImFsbG93QW5vbnltb3VzQ2hhdCI6dHJ1ZSwiemlwQ29kZSI6bnVsbCwiZGVsaXZlcnlUeXBlIjpbIlNFTExFUl9ERUxJVkVSWSIsIkJVWUVSX1BJQ0tVUCIsIkJVWUVSX1BJQ0tVUF9GUk9NX0JSQU5DSCJdLCJtYXhEZWxpdmVyeVJhbmdlIjowLCJmcmVlRGVsaXZlcnlSYW5nZSI6MjAwLCJtaW5GcmVlRGVsaXZlcnlPcmRlciI6NTAwMCwicGVyTWlsZUNvc3QiOjIsImF2YWlsYWJpbGl0eSI6IjA4OjAwLTE3OjAwIiwiZXN0aW1hdGVkRGVsaXZlcnlUaW1lIjpbIjYwXzQwIl0sImF2YWlsYWJpbGl0eUJyYW5jaCI6IjA4OjAwLTE3OjAwIiwibWlkZGxlTmFtZSI6Im51bGwiLCJsYXN0TmFtZSI6InlhdnV6IiwiZmxleGlibGVEZWxpdmVyeU9wdGlvbnMiOltdfQ.KH-1CDTiAReKS-8DO-9QKe4UMOme7p0vi6PXjAb0pjEORBb-mA5QYXnY6DasLWmvooMCIMKaquR1m7jrTDan7oOA2i1hFMExf0cwVc9UdDbaMtHc9AKw-z9Sp2kTS5LBA0zs_szFZtrhfhMPuoIgpCeH27hJBRKfoZ8tooKytTU7JyCB7LfR4hiNGllAi1XyvggjJ7Q45R_qirW8GbhEClqurvLKs7id181Knvqpj_dVupMtpUswUwzUC6V8a2RPqsvbWYfhPq_vBbQQFg9gY9FkGa6-vxl89-3OYq0SN1sFGxAE1-rJF_RwRdXzalapbdD_Z0QjHVJQHqvtYSWfUw"),
    SELLER_1_TOKEN(true,0,"seller_urban1@yopmail.com","Seller1/","","","","","eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2Nzk0OTkzMTEsImV4cCI6MTcxMDYwMzMxMSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImVtYWlsIjoic2VsbGVyX3VyYmFuMUB5b3BtYWlsLmNvbSIsImlkIjoxNzc2LCJmaXJzdE5hbWUiOiJSdXpnYXIiLCJwaWN0dXJlIjpudWxsLCJnb29nbGVJZCI6bnVsbCwiZmFjZWJvb2tJZCI6bnVsbCwibGlua2VkaW5JZCI6bnVsbCwiZ2l0aHViSWQiOm51bGwsImFwcGxlSWQiOm51bGwsImlzVmVyaWZpZWQiOmZhbHNlLCJwaG9uZSI6bnVsbCwiZGV2aWNlVG9rZW4iOiIwIiwiY3JlYXRlZCI6eyJkYXRlIjoiMjAyMy0wMi0yNCAyMDo0OTo0Mi4wMDAwMDAiLCJ0aW1lem9uZV90eXBlIjozLCJ0aW1lem9uZSI6IlVUQyJ9LCJwYXlwYWxBY2NvdW50SWQiOm51bGwsImxhdCI6MzcuNzc5ODcyMSwibG5nIjotMTIyLjI4MjE4NTUsImJyb3dzZXJOb3RpZmljYXRpb25zIjpmYWxzZSwiYWxsb3dBbm9ueW1vdXNDaGF0Ijp0cnVlLCJ6aXBDb2RlIjpudWxsLCJkZWxpdmVyeVR5cGUiOlsiQlVZRVJfUElDS1VQX0ZST01fQlJBTkNIIiwiU0VMTEVSX0RFTElWRVJZIl0sIm1heERlbGl2ZXJ5UmFuZ2UiOjUwMCwiZnJlZURlbGl2ZXJ5UmFuZ2UiOjE1MCwibWluRnJlZURlbGl2ZXJ5T3JkZXIiOjUwLCJwZXJNaWxlQ29zdCI6MiwiYXZhaWxhYmlsaXR5IjoiIiwiZXN0aW1hdGVkRGVsaXZlcnlUaW1lIjpbIjEyMF8zMCJdLCJhdmFpbGFiaWxpdHlCcmFuY2giOiIwMTowMC0wNTowMCIsIm1pZGRsZU5hbWUiOiIiLCJsYXN0TmFtZSI6IlNha2luIiwiZmxleGlibGVEZWxpdmVyeU9wdGlvbnMiOltdfQ.l_JW2r6RdJGVEi3AvEIzT3Jhg7kDnBPXYA3lDwZMEhHBhuBw_5dXD_nQptCFy8s1ZZ45Q2hMKIa362lSeTU6Zb-KVEt6y3Xq5-Te343xeV5akSdTmrziXXRZOqpyUxUxl0w5AMlUhgADtZr_tuGq7zx-bEL-KC9V4RV-r3VAIz8kJUn1myM3sonrHnpa1XLdHjVt1DJ_-LIpaypHLguwlJUuU_dxNOHEOoxdfHClwAHTWtxayc8l9o-vST-XNuXLSuH0olWkBZT8D05XaD55XRd4qwQDR8yi5L3AaSK3Cj4KWhVuJVKanHfYNTtg2IXC7IcPBrXBPRKuh476QOBVTQ");

    private boolean isTest;
    private int userId;
    private String token, firstName, middleName, lastName, password, email, postalCode;

    USER(boolean isTest, int userId, String email, String password, String firstName, String middleName, String lastName, String postalCode, String token) {
        this.isTest = isTest;
        this.userId = userId;
        this.token = token;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.password = password;
        this.email = email;
        this.postalCode = postalCode;
    }

    USER(boolean isTest, String email, String password ,String postalCode ) {
        this.isTest = isTest;
        this.userId = userId;
        this.token = token;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.password = password;
        this.email = email;
        this.postalCode = postalCode;
    }

    public boolean isTest() {
        return isTest;
    }

    public int getUserId() {
        return userId;
    }

    public String getToken() {
        return token;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getMiddleName() {
        return middleName;
    }

    public String getLastName() {
        return lastName;
    }

    public String getPassword() {
        return password;
    }

    public String getEmail() {
        return email;
    }

    public String getPostalCode() {
        return postalCode;
    }
}
